"""add AI-powered fields to file model

Revision ID: 2f58457b1cf4
Revises: 4e42512036ec
Create Date: 2025-09-10 01:58:38.068723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f58457b1cf4'
down_revision = '4e42512036ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_hash', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('image_metadata', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('image_metadata')
        batch_op.drop_column('quality_score')
        batch_op.drop_column('image_hash')
        batch_op.drop_column('ai_tags')
        batch_op.drop_column('ai_description')

    # ### end Alembic commands ###
