"""create file and upload_session tables

Revision ID: 3a1b2c3d4e5f
Revises: 2f58457b1cf4
Create Date: 2025-09-11 00:58:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1b2c3d4e5f'
down_revision = '2f58457b1cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('s3_url', sa.String(length=1000), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=100), nullable=True),
    sa.Column('ai_description', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=500), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('image_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('upload_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('uploaded_chunks', sa.Integer(), nullable=True),
    sa.Column('temp_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_session')
    op.drop_table('file')
    # ### end Alembic commands ###
