"""add advanced features to file model

Revision ID: 4e42512036ec
Revises: cc60b91e7bc6
Create Date: 2025-09-10 01:51:48.746387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e42512036ec'
down_revision = 'cc60b91e7bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('folder', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('share_token', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_file_share_token', ['share_token'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_used', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('storage_limit', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('storage_limit')
        batch_op.drop_column('storage_used')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint('uq_file_share_token', type_='unique')
        batch_op.drop_column('share_token')
        batch_op.drop_column('description')
        batch_op.drop_column('tags')
        batch_op.drop_column('folder')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
